apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orleans-kubernetes-app-hpa
  namespace: orleans-testing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orleans-kubernetes-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
