apiVersion: v1
kind: Namespace
metadata:
  name: orleans-testing
---
apiVersion: v1
kind: Secret
metadata:
  name: orleans-db-secret
  namespace: orleans-testing
type: Opaque
data:
  storage-connection-string: ""
