apiVersion: apps/v1
kind: Deployment
metadata:
  name: orleans-kubernetes-app
  namespace: orleans-testing
  labels:
    orleans/serviceId: orleans-kubernetes-app
spec:
  selector:
    matchLabels:
      orleans/serviceId: orleans-kubernetes-app
  replicas: 3
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        orleans/serviceId: orleans-kubernetes-app
        orleans/clusterId: orleans-kubernetes-app
    spec:
      containers:
        - name: silo
          image: aroman35/orleans-kubernetes-silo:1.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 11111
            - containerPort: 30000
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: DASHBOARDOPTIONS__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dashboard-settings
                  key: password
            - name: DASHBOARDOPTIONS__USERNAME
              valueFrom:
                secretKeyRef:
                  name: dashboard-settings
                  key: username
            - name: CONNECTIONSTRINGS__PGSQL
              valueFrom:
                secretKeyRef:
                  name: orleans-db-secret
                  key: storage-connection-string
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/clusterId']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
              value: "120"
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
      terminationGracePeriodSeconds: 180
      imagePullSecrets:
        - name: orleans-db-secret
        - name: dashboard-settings
      volumes:
        - name: appsettings-volume
          configMap:
            name: orleans-appsettings
