kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: orleans-hosting
  namespace: orleans-testing
rules:
  - apiGroups: [ "" ]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete", "patch"]
