apiVersion: apps/v1
kind: Deployment
metadata:
  name: orleans-kubernetes-app
  namespace: {{ .Values.namespace }}
  labels:
    orleans/serviceId: orleans-kubernetes-app
spec:
  selector:
    matchLabels:
      orleans/serviceId: orleans-kubernetes-app
  replicas: 3
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        orleans/serviceId: orleans-kubernetes-app
        orleans/clusterId: orleans-kubernetes-app
    spec:
      serviceAccountName: orleans-sa
      containers:
        - name: silo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: silo
              containerPort: {{ .Values.ports.silo }}
            - name: gateway
              containerPort: {{ .Values.ports.gateway }}
            - name: http
              containerPort: {{ .Values.ports.http }}
          env:
            - name: ASPNETCORE_URLS
              value: {{ .Values.env.ASPNETCORE_URLS | quote }}
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: DASHBOARDOPTIONS__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dashboard-settings
                  key: password
            - name: DASHBOARDOPTIONS__USERNAME
              valueFrom:
                secretKeyRef:
                  name: dashboard-settings
                  key: username
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/clusterId']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
              value: {{ .Values.env.DOTNET_SHUTDOWNTIMEOUTSECONDS | quote }}
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          resources:
            requests:
              cpu: "125m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /health/startup
              port: {{ .Values.ports.http }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.ports.http }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.ports.http }}
            initialDelaySeconds: 15
            periodSeconds: 5
      terminationGracePeriodSeconds: 180
      imagePullSecrets:
        - name: dashboard-settings
      volumes:
        - name: appsettings-volume
          configMap:
            name: orleans-appsettings
