apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orleans-hosting-binding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: orleans-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: orleans-hosting
  apiGroup: rbac.authorization.k8s.io
