apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orleans-crd-access
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["orleans.dot.net"]
    resources: ["*"]
    verbs: ["*"]
